updated all gems to install rails 6
Vivino/wrest pull request #12
Opened 2020-10-27 15:59 UTC by andreorvalho

This is a start of rails 6 upgrade

2020-10-30 13:31 UTC, corthmann requested changes
Nice to get dependencies updated here :heart:

2020-10-30 13:31 UTC, corthmann commented on Gemfile
> +  gem 'multipart-post'
we need this fixed as I don't think wrest works with 1.x of this gem. I'd suggest:
```suggestion
  gem 'multipart-post',  '>= 2.0', '< 3.0'
```

2020-10-30 13:31 UTC, corthmann commented on lib/wrest/caching/redis.rb
> +  gem 'redis', '~> 4'
the comment below is now untrue

2021-02-02 08:07 UTC, corthmann approved these changes

2021-03-23 12:17 UTC, ksza approved these changes
👍

2021-10-06 12:18 UTC, andersklenke commented
We're upgrading the Rails version to 6.1 in wine-admin. Can we have this PR merged?

2022-05-10 07:36 UTC, merged